### ISSUE TITLE
minimum stability issues

### ISSUE THREAD

**Issue by hiranipradeep** [gallib/laravel-short-url#11]
There are some depending issues of laravel-short-url package
I have "laravel/framework": "5.7.*".

I am getting issues while I run this command
composer require gallib/laravel-short-url

Problem 1
    - gallib/laravel-short-url 1.4.2 requires symfony/dom-crawler ^4.2 -> satisfiable by symfony/dom-crawler[4.2.x-dev, 4.3.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.2, v4.2.3] but these conflict with your requirements or minimum-stability.
    - gallib/laravel-short-url 1.4.1 requires illuminate/routing 5.6.* -> satisfiable by illuminate/routing[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9] but these conflict with your requirements or minimum-stability.
    - gallib/laravel-short-url 1.4.0 requires illuminate/routing 5.6.* -> satisfiable by illuminate/routing[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9] but these conflict with your requirements or minimum-stability.
    - Installation request for gallib/laravel-short-url ^1.4 -> satisfiable by gallib/laravel-short-url[1.4.0, 1.4.1, 1.4.2].

**Comment by gallib** [comment]
Hi @hiranipradeep you must have conflicts with your project requirements.

Have you tried on a fresh laravel installation ?
