### ISSUE TITLE
Proposal : Expiration date

### ISSUE THREAD

**Issue by Nuranto** [gallib/laravel-short-url#13]
Functionnality proposal : 
Add an optional column `expires_at`.
Then, a daily or weekly cron comes cleanup.

Can be useful for temporary short links. For instance, if we send shortened url by mail to validate the email, it doesn't need to stay in time.

**Comment by gallib** [comment]
Hi,

this is definitively the next feature i'd like to work on.

It's not so easy thought if you think about it 5 minutes. 
- Which datepicker to use ?
- Redirect with a 302 ?
- Allow to reuse shortcode once the url has expired ?
- Others ?

I will start working on it after my move

**Comment by Nuranto** [comment]
**Which datepicker to use ?**

I think a simple input with type date or datetime-local ? Then, everyone is free to surcharge the view ?

**Redirect with a 302 ?**

Seems a logical choice to me.

**Allow to reuse shortcode once the url has expired ?**

I would say yes

**Others ?**

Maybe a 410 status after expiration ?

**Comment by gallib** [comment]
Hi   @Nuranto,

see newly tagged [v1.5.0](https://github.com/gallib/laravel-short-url/releases/tag/1.5.0)

Hope it will fit your needs
