### ISSUE TITLE
Feature Request: Multi-User Support

### ISSUE THREAD

**Issue by erdmenchen** [gallib/laravel-short-url#17]
Hi there!
I very much like this simple and clean package and would love to use it.
But currently my use case for a multi-user scenario prevents me, because a shortened url is not associated with the user, that authored this url.

It would be just a small extension to add a `user_id` column to the url table.
That way, we could filter to only show the urls authored by the current user, so that no urls are shown from other users and so that users cannot edit urls from other users.

What do you think about this?
If you do not consider this functionality to be implemented in the package, how could I extend the package myself to match my use case?

**Comment by gallib** [comment]
Hi @erdmenchen 

Thanks for your feedback.

Add a user_id could be something we can implement (with [Illuminate/Auth](https://github.com/illuminate/auth) I think). 
IMHO this column should be optionnal as the package should continue to work for guests.

I0ll try to work on this feature on the next weeks.

**Comment by gallib** [comment]
Hi @erdmenchen 

Hope that [1.6.0](https://github.com/gallib/laravel-short-url/releases/tag/1.6.0) will satisfies your needs!
